# Generated by Django 4.1.13 on 2024-02-19 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codart', '0004_remove_profile_image_dart_code_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dart',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dart_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dart',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='dart_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='dart_dislikes',
            field=models.ManyToManyField(blank=True, related_name='dart_dislikes', to='codart.dart'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dart_likes',
            field=models.ManyToManyField(blank=True, related_name='dart_likes', to='codart.dart'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
