# Generated by Django 4.1.13 on 2024-02-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codart', '0005_dart_dislikes_dart_likes_profile_dart_dislikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
    ]
