# Generated by Django 4.1.13 on 2024-02-24 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codart', '0006_newsstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dart',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='dart_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_darts',
            field=models.ManyToManyField(blank=True, related_name='dart_saved', to='codart.dart'),
        ),
        migrations.AlterField(
            model_name='dart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darts', to=settings.AUTH_USER_MODEL),
        ),
    ]
