# Generated by Django 4.1.13 on 2024-02-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codart', '0007_dart_saved_by_profile_saved_darts_alter_dart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='saved_darts',
            new_name='dart_saved',
        ),
    ]
