# Generated by Django 4.1.13 on 2024-02-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codart', '0008_rename_saved_darts_profile_dart_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dart',
            name='saved_by',
        ),
    ]
