# Generated by Django 4.1.13 on 2024-02-25 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codart', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dart',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='dart_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
